name: countries
description: Dart library for country data
version: 0.1.0
homepage: https://github.com/mathatan/countriesm

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  built_value: ^8.0.0
  computer: ^1.0.2
  build: ^1.6.2
  universal_io: ^2.0.0
  stringmatcher: ^1.0.0

#dependencies:
#  path: ^1.6.0

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
  build_runner: ^1.7.4
  source_gen: ^0.9.4+7
  built_value_generator: ^8.0.0

dependency_overrides:
  analyzer: ^1.1.0
