name: countries
description: A starting point for Dart libraries or applications.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  built_value: ^7.0.9
  computer: ^1.0.2
  build: ^1.2.2  

#dependencies:
#  path: ^1.6.0

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
  build_runner: ^1.7.4
  source_gen: ^0.9.4+7
  built_value_generator: ^7.0.9  
